# Generated by Django 3.0.5 on 2020-05-01 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_Number', models.CharField(max_length=50, null=True)),
                ('User_ID', models.CharField(max_length=50, null=True)),
                ('Report_Number', models.CharField(max_length=50, null=True)),
                ('Issue_Date', models.DateField()),
                ('Standard_ID', models.CharField(max_length=50, null=True)),
                ('Location_ID', models.CharField(max_length=50, null=True)),
                ('Model_Number', models.CharField(max_length=50, null=True)),
                ('Slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Number', models.CharField(max_length=50, null=True)),
                ('Product_Name', models.CharField(max_length=50, null=True)),
                ('Cell_Technology', models.CharField(max_length=50, null=True)),
                ('Cell_Manufacturer', models.CharField(max_length=50, null=True)),
                ('Number_of_Cells', models.CharField(max_length=50, null=True)),
                ('Number_of_Cells_in_Series', models.CharField(max_length=50, null=True)),
                ('Number_of_Series_in_Strings', models.CharField(max_length=50, null=True)),
                ('Number_of_Diodes', models.CharField(max_length=50, null=True)),
                ('Product_Length', models.CharField(max_length=50, null=True)),
                ('Product_Width', models.CharField(max_length=50, null=True)),
                ('Product_Weight', models.CharField(max_length=50, null=True)),
                ('Superstate_Type', models.CharField(max_length=50, null=True)),
                ('Superstate_Manufacturer', models.CharField(max_length=50, null=True)),
                ('Substrate_Type', models.CharField(max_length=50, null=True)),
                ('Substrate_Manufacturer', models.CharField(max_length=50, null=True)),
                ('Frame_Type', models.CharField(max_length=50, null=True)),
                ('Frame_Adhesive', models.CharField(max_length=50, null=True)),
                ('Encapsulate_Type', models.CharField(max_length=50, null=True)),
                ('Encapsulant_Manufacturer', models.CharField(max_length=50, null=True)),
                ('Junction_Box_Type', models.CharField(max_length=50, null=True)),
                ('Junction_Box_Manufacturer', models.CharField(max_length=50, null=True)),
                ('Slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('clientID', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_ID', models.CharField(max_length=50, null=True)),
                ('Service_Name', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=50, null=True)),
                ('Is_FI_Required', models.CharField(max_length=50, null=True)),
                ('FI_Frequency', models.CharField(max_length=50, null=True)),
                ('Slug', models.SlugField(max_length=200, unique=True)),
                ('Standard_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solarpvAPP.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Registered_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=50, null=True)),
                ('clientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solarpvAPP.Registered_Company')),
            ],
        ),
    ]
