# Generated by Django 3.0.5 on 2020-05-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarpvAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='Slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Slug',
        ),
    ]
