# Generated by Django 3.0.5 on 2020-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpvAPP', '0002_auto_20200502_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='cell_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='email_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='office_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
